### ISSUE TITLE
Don't seem to work with OLA 5.10 with internal database

### ISSUE THREAD

**Issue by henrikadolfsson** [petlof/liveresults#42]
The latest version of OLA (5.10.1) don't seem to be compatible with liveresults.

When trying to open a internal OLA db I get the following error alert:

![image](https://user-images.githubusercontent.com/1379189/56853742-362e6b00-692c-11e9-8ebf-76159d556cd5.png)

It works fine when I downgrade to OLA 5.5 on the same competition.

**Comment by fredricj** [comment]
In OLA 5.10 the internal database engine creates the internal database in a newer format with a different extension (.mv.db instead of .h2.db). The database engine excepts the path without the extension so for the old format Emmaclient automatically removes the extension, but this doesn't happen for the newer format.
Workaround is to specify the database without the extension.
The fix is to update the code to handle the new extension as well.
In addition it should add IFEXISTS=TRUE to the connection to avoid autocreating a new empty database when a non-existing database is selected, which is what happened above

**Comment by fredricj** [comment]
This should be fixed by #44 . So far I couldn't get the IFEXISTS=TRUE to work, it only gives an error message that it couldn't find the database

**Comment by petlof** [comment]
This is fixed by commit 4317f5584c0c24b6f0cc2176c739d9eeb3d4fe8b, 
Will be released as version 1.3.0 today
